### 책 등록
POST localhost:8080/api/v1/book
Content-Type: application/json

{
  "title": "제목1",
  "author": "작가1"
}

### 책 목록 보기
GET localhost:8080/api/v1/book

### 책 한건 보기
GET localhost:8080/api/v1/book/1

### 책 삭제
DELETE localhost:8080/api/v1/book/1

### 책 수정
PUT localhost:8080/api/v1/book/1
Content-Type: application/json

{
  "title": "제목수정",
  "author": "작가수정"
}